#use_frameworks!

platform :ios, '11.0'

target 'YFAdsFramework_Example' do
  pod 'YFAdsFramework', :path => '../'
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'LookinServer', :configurations => ['Debug']
end
